version: "3.1"
services:
  odoo_main:
    build:
      context: ./
      dockerfile: dockerfile-main
    depends_on:
      - db-main
    ports:
      - "8069:8069"
    volumes:
      - data-main:/var/lib/odoo
      - ./config/odoo-main.conf:/etc/odoo/odoo.conf
      # - ./custom-addons-main:/mnt/extra-addons
    env_file: myenvfile-main.env
    networks:
      - main_network

  odoo_staging:
    build:
      context: ./
      dockerfile: dockerfile-staging
    image: odoo:18.0
    env_file: myenvfile-staging.env
    depends_on:
      - db-staging
    ports:
      - "8070:8080"
    volumes:
      - data-staging:/var/lib/odoo
      - ./config/odoo-staging.conf:/etc/odoo/odoo.conf
      # - ./custom-addons-staging:/mnt/extra-addons
    networks:
      - staging_network
  db-main:
    image: postgres:15
    env_file: myenvfile-main.env
    volumes:
      - db-main:/var/lib/pgsql/data/pgdata
    networks:
      - main_network
  db-staging:
    image: postgres:15
    env_file: myenvfile-staging.env
    volumes:
      - db-staging:/var/lib/pgsql/data/pgdata
    networks:
      - staging_network

volumes:
  data-main:
  data-staging:
  db-main:
  db-staging:

networks:
  main_network:
  staging_network:
