apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: "postgres"
  POSTGRES_USER: "odoo18-main"
  POSTGRES_PASSWORD: "odoo18-main"
  PGDATA: "/var/lib/postgresql/data/pgdata"
